### ISSUE TITLE
What about strong types for ApolloClient.query() or query.mutate()?

### ISSUE THREAD

**Issue by dko-slapdash** [PabloSzx/graphql-tag-ts#3]
Hi.

When calling e.g. `const res = await client.mutate({ mutation: MyMutation })` where MyMutation is created via this library's strongly typed DocumentNode, there are no strong types on the result variable.

Is it possible to change method signatures in ApolloClient (and DataProxy BTW) too?

If not, there would be an alternative approach which could've been merged in the library:

```ts
// in the library:
export type DataOf<T> = T extends DocumentNode<infer TData, any> ? TData : never;
export type VariablesOf<T> = T extends DocumentNode<any, infer TVariables> ? TVariables : never;
// in the caller code:
const res = await client.mutate<DataOf<typeof MyMutation>, VariablesOf<typeof MyMutation>>(
  { mutation: MyMutation }
);
```

It's uglier, but does the job

P.S.
Awesome approach in the library! I used to implement something similar, but much more intrusive (i.e. I had DocumentNodeX and variants of hooks like useQueryX which were used everywhere, but your approach is much nicer).

P.P.S.
Looks like the approach with class method signature substitution doesn't fully work: it successfully infers type for Data, but always prefer the ad-hoc values for Variables vs. the ones extracted from DocumentNode<> (and doesn't check for conflicts). This is what I eventually tried:

```ts
declare module "apollo-client" {
  export class ApolloClient<TCacheShape> {
    mutate<TDoc>(
      options: {
        mutation: TDoc;
        context?: any;
        fetchPolicy?: FetchPolicy;
      } & MutationBaseOptions<DataOf<TDoc>, VariablesOf<TDoc>>
    ): Promise<FetchResult<DataOf<TDoc>>>;
  }
}
...
// although res type is inferred, we can pass whatever to variables, and there will be no errors
const res = await client.mutate({ mutation: My, variables: { canPassWhatever: 44 } });
```

**Comment by PabloSzx** [comment]
I was looking into how to do the type augmentation into ApolloClient directly and it's definitely more tricky than how it's being done with @apollo/react-hooks, since the "type architecture" is all over the place, right now I don't have much time to look into it, eventually I could.

**Comment by PabloSzx** [comment]
Closing in favor of https://github.com/dotansimha/graphql-typed-document-node and included TypedQueryDocumentNode in graphql-js
